version: 2
jobs:
  build:
    machine: 
      docker_layer_caching: false
    steps: 
      - checkout

  test:
    machine:
        docker_layer_caching: false
    steps:
      - checkout
      - run:
          command: |
            cd tests
            docker-compose down --v
            docker-compose build
            docker-compose run tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - test